# Generated by Django 4.2.17 on 2025-05-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Contenido'),
        ),
    ]
