# Generated by Django 5.2.1 on 2025-05-27 16:54

from django.db import migrations, models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_options_page_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
